
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/exams
    username: postgres
    password: 123456
    
  # use only if you need debug (1)
  jpa:
#    show-sql: true 
    properties:
      hibernate:
#        format_sql: true
        # see https://stackoverflow.com/questions/31585698/spring-boot-jpa2-hibernate-enable-second-level-cache
        cache:
          use_second_level_cache: true
          #optional - turn on query cache.
          use_query_cache: true 
          region:
            #required - classpath to cache region factory.
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

       
    # # only initially for prototype, then use flyway
    # # hibernate:
    # #   ddl-auto: create-drop
  # flyway:
  #   locations: classpath:/db/migration,classpath:/db/testdata
  
  # change max page size (in order to support excel download)
  # https://stackoverflow.com/questions/33675349/spring-data-rest-max-page-size-does-not-seem-to-be-working
  # TODO: remove this when excel download improve
  data:
    web.pageable.max-page-size: 10000

# use only if you need debug (1)
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
        # type.descriptor.sql.BasicBinder: TRACE # to show parameter (values) of sql queries

# monitoring, more on: https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-actuator
# management:
#   endpoints:
#     web: 
#       exposure:
#         include: "*"

# swagger
# springdoc:
#   api-docs:
#     path: /api-docs
# security:
#   jwt:
#     token:
#       secret-key: 33d9b2ae-0275-11eb-adc1-0242ac120002

# logging
# logbook: 
#   include: /**
#   exclude: /actuator/health
# more on https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-logging-file-output
# logging.file.name = /var/tmp/casilla.log
# logging.level.org.zalando.logbook: TRACE

cors_origin: "*"