spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
cors_origin: ${CORS_ORIGIN}

security:
  jwt:
    token: 
      secret-key: ${JWT_SECRET_KEY}
      expire-length: 7200000 # 2 hours
